export const SUBMIT_NAME = 'SUBMIT_NAME'
export const SUBMIT_TOKEN = 'SUBMIT_TOKEN'
export const RECIEVE_UUID = 'RECIEVE_UUID'
export const ADD_TODO = 'ADD_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
